/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.genivi.NodeStateManager.LifeCycleConsumer.xml -a LifeCycleConsumerAdaptor -l LifeCycleConsumer -i lifecycleconsumer.h
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "lifecycleconsumeradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class LifeCycleConsumerAdaptor
 */

LifeCycleConsumerAdaptor::LifeCycleConsumerAdaptor(LifeCycleConsumer *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

LifeCycleConsumerAdaptor::~LifeCycleConsumerAdaptor()
{
    // destructor
}

int LifeCycleConsumerAdaptor::LifecycleRequest(uint Request, uint RequestId)
{
    // handle method call org.genivi.NodeStateManager.LifeCycleConsumer.LifecycleRequest
    return parent()->LifecycleRequest(Request, RequestId);
}

