/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.genivi.NodeStateManager.LifeCycleConsumer.xml -a LifeCycleConsumerAdaptor -l LifeCycleConsumer -i lifecycleconsumer.h
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef LIFECYCLECONSUMERADAPTOR_H
#define LIFECYCLECONSUMERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "lifecycleconsumer.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.genivi.NodeStateManager.LifeCycleConsumer
 */
class LifeCycleConsumerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.genivi.NodeStateManager.LifeCycleConsumer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.genivi.NodeStateManager.LifeCycleConsumer\">\n"
"    <method name=\"LifecycleRequest\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"Request\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"RequestId\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"ErrorCode\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    LifeCycleConsumerAdaptor(LifeCycleConsumer *parent);
    virtual ~LifeCycleConsumerAdaptor();

    inline LifeCycleConsumer *parent() const
    { return static_cast<LifeCycleConsumer *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int LifecycleRequest(uint Request, uint RequestId);
Q_SIGNALS: // SIGNALS
};

#endif
